// <auto-generated>
//     Generated by tools/Generate-Strings.py from the table in that script.
//     Do not edit by hand: add the key there and regenerate, so the English and
//     Turkish tables cannot drift apart.
// </auto-generated>

// Auto-generated files opt out of the nullable context, so state it explicitly.
#nullable enable
using System.Globalization;
using System.Resources;

namespace SonarTray.Resources;

/// <summary>
/// Localised UI strings. English is the fallback for every language but Turkish.
///
/// Both languages are embedded in the main assembly rather than shipped as a culture
/// satellite, because satellite assemblies are not bundled into a PublishSingleFile exe
/// and the release is a single file.
/// </summary>
public static class Strings
{
    private static readonly ResourceManager English =
        new("SonarTray.Resources.Strings", typeof(Strings).Assembly);

    private static readonly ResourceManager Turkish =
        new("SonarTray.Resources.Strings_tr", typeof(Strings).Assembly);

    /// <summary>An explicit language choice; null follows <see cref="CultureInfo.CurrentUICulture"/>.</summary>
    public static CultureInfo? Culture { get; set; }

    /// <summary>Every language code this build actually has strings for.</summary>
    public static IReadOnlyList<string> SupportedLanguages { get; } = new[] { "en", "tr" };

    /// <summary>Matches on the two-letter code, so tr-TR and tr-CY both get Turkish.</summary>
    private static ResourceManager Active
    {
        get
        {
            var culture = Culture ?? CultureInfo.CurrentUICulture;
            return culture.TwoLetterISOLanguageName.Equals("tr", StringComparison.OrdinalIgnoreCase)
                ? Turkish
                : English;
        }
    }

    /// <summary>
    /// Falls back to English and then to the key itself, so a missing resource is visible
    /// in the UI but never throws.
    /// </summary>
    public static string Get(string key)
        => Active.GetString(key, CultureInfo.InvariantCulture)
           ?? English.GetString(key, CultureInfo.InvariantCulture)
           ?? key;

    /// <summary>Formats a resource containing placeholders, in the active display culture.</summary>
    public static string Format(string key, params object[] args)
        => string.Format(Culture ?? CultureInfo.CurrentUICulture, Get(key), args);

    /// <summary>Master</summary>
    public static string Channel_Master => Get("Channel_Master");

    /// <summary>Game</summary>
    public static string Channel_Game => Get("Channel_Game");

    /// <summary>Chat</summary>
    public static string Channel_Chat => Get("Channel_Chat");

    /// <summary>Media</summary>
    public static string Channel_Media => Get("Channel_Media");

    /// <summary>Microphone</summary>
    public static string Channel_Mic => Get("Channel_Mic");

    /// <summary>Aux</summary>
    public static string Channel_Aux => Get("Channel_Aux");

    /// <summary>Sonar Mixer</summary>
    public static string Panel_Title => Get("Panel_Title");

    /// <summary>Start with Windows</summary>
    public static string Panel_StartWithWindows => Get("Panel_StartWithWindows");

    /// <summary>Exit</summary>
    public static string Panel_Exit => Get("Panel_Exit");

    /// <summary>Settings</summary>
    public static string Panel_Settings => Get("Panel_Settings");

    /// <summary>Open SteelSeries GG</summary>
    public static string Panel_OpenGg => Get("Panel_OpenGg");

    /// <summary>Refresh</summary>
    public static string Panel_Refresh => Get("Panel_Refresh");

    /// <summary>Mute / unmute</summary>
    public static string Panel_MuteToggle => Get("Panel_MuteToggle");

    /// <summary>The selected device is disconnected, or the redirection is not running</summary>
    public static string Panel_DeviceMissing => Get("Panel_DeviceMissing");

    /// <summary>Output device</summary>
    public static string Panel_Device => Get("Panel_Device");

    /// <summary>Input device</summary>
    public static string Panel_DeviceCapture => Get("Panel_DeviceCapture");

    /// <summary>Volume</summary>
    public static string Panel_Volume => Get("Panel_Volume");

    /// <summary>Looking for Sonar…</summary>
    public static string Status_Searching => Get("Status_Searching");

    /// <summary>Connected</summary>
    public static string Status_Connected => Get("Status_Connected");

    /// <summary>Stream mode</summary>
    public static string Status_StreamMode => Get("Status_StreamMode");

    /// <summary>Sonar not found</summary>
    public static string Status_NotFound => Get("Status_NotFound");

    /// <summary>Sonar not found</summary>
    public static string Offline_Title => Get("Offline_Title");

    /// <summary>Is SteelSeries GG running?</summary>
    public static string Offline_Hint => Get("Offline_Hint");

    /// <summary>Try again</summary>
    public static string Offline_Retry => Get("Offline_Retry");

    /// <summary>Classic</summary>
    public static string Mode_Classic => Get("Mode_Classic");

    /// <summary>Stream</summary>
    public static string Mode_Stream => Get("Mode_Stream");

    /// <summary>Switch mode</summary>
    public static string Mode_Switch => Get("Mode_Switch");

    /// <summary>Switch to Classic</summary>
    public static string Mode_SwitchToClassic => Get("Mode_SwitchToClassic");

    /// <summary>Switch to Stream</summary>
    public static string Mode_SwitchToStream => Get("Mode_SwitchToStream");

    /// <summary>Sonar is in Stream mode</summary>
    public static string Stream_Title => Get("Stream_Title");

    /// <summary>This tool only controls Classic mode.</summary>
    public static string Stream_Hint => Get("Stream_Hint");

    /// <summary>Stream</summary>
    public static string Stream_Streaming => Get("Stream_Streaming");

    /// <summary>Monitor</summary>
    public static string Stream_Monitoring => Get("Stream_Monitoring");

    /// <summary>Shortcuts</summary>
    public static string Hotkeys_Title => Get("Hotkeys_Title");

    /// <summary>Restore defaults</summary>
    public static string Hotkeys_Reset => Get("Hotkeys_Reset");

    /// <summary>Click a shortcut and press the new combination. Esc cancels, Del cl...</summary>
    public static string Hotkeys_Help => Get("Hotkeys_Help");

    /// <summary>Remove</summary>
    public static string Hotkeys_Clear => Get("Hotkeys_Clear");

    /// <summary>Remove shortcut</summary>
    public static string Hotkeys_ClearTip => Get("Hotkeys_ClearTip");

    /// <summary>Press a key…</summary>
    public static string Hotkeys_PressKey => Get("Hotkeys_PressKey");

    /// <summary>None</summary>
    public static string Hotkeys_None => Get("Hotkeys_None");

    /// <summary>Another application already owns this combination</summary>
    public static string Hotkeys_Taken => Get("Hotkeys_Taken");

    /// <summary>Mute / unmute microphone</summary>
    public static string Action_MicMute => Get("Action_MicMute");

    /// <summary>Mute / unmute master</summary>
    public static string Action_MasterMute => Get("Action_MasterMute");

    /// <summary>Master volume up</summary>
    public static string Action_MasterUp => Get("Action_MasterUp");

    /// <summary>Master volume down</summary>
    public static string Action_MasterDown => Get("Action_MasterDown");

    /// <summary>Show / hide panel</summary>
    public static string Action_TogglePanel => Get("Action_TogglePanel");

    /// <summary>Game volume up</summary>
    public static string Action_GameUp => Get("Action_GameUp");

    /// <summary>Game volume down</summary>
    public static string Action_GameDown => Get("Action_GameDown");

    /// <summary>Mute / unmute game</summary>
    public static string Action_GameMute => Get("Action_GameMute");

    /// <summary>Chat volume up</summary>
    public static string Action_ChatUp => Get("Action_ChatUp");

    /// <summary>Chat volume down</summary>
    public static string Action_ChatDown => Get("Action_ChatDown");

    /// <summary>Mute / unmute chat</summary>
    public static string Action_ChatMute => Get("Action_ChatMute");

    /// <summary>Media volume up</summary>
    public static string Action_MediaUp => Get("Action_MediaUp");

    /// <summary>Media volume down</summary>
    public static string Action_MediaDown => Get("Action_MediaDown");

    /// <summary>Mute / unmute media</summary>
    public static string Action_MediaMute => Get("Action_MediaMute");

    /// <summary>SonarTray - master muted</summary>
    public static string Tray_Muted => Get("Tray_Muted");

    /// <summary>SonarTray - master {0}%</summary>
    public static string Tray_Volume => Get("Tray_Volume");

    /// <summary>SonarTray - Sonar is in Stream mode</summary>
    public static string Tray_StreamMode => Get("Tray_StreamMode");

    /// <summary>SonarTray - looking for Sonar…</summary>
    public static string Tray_Searching => Get("Tray_Searching");

    /// <summary>SonarTray - Sonar not found</summary>
    public static string Tray_NotFound => Get("Tray_NotFound");

    /// <summary>Muted</summary>
    public static string Osd_Muted => Get("Osd_Muted");

    /// <summary>{0}%</summary>
    public static string Osd_Percent => Get("Osd_Percent");

    /// <summary>(not connected)</summary>
    public static string Device_NotConnected => Get("Device_NotConnected");

    /// <summary>Audio profile</summary>
    public static string Profiles_Title => Get("Profiles_Title");

    /// <summary>Loading…</summary>
    public static string Profiles_Loading => Get("Profiles_Loading");

    /// <summary>No profiles</summary>
    public static string Profiles_None => Get("Profiles_None");

    /// <summary>Presets</summary>
    public static string Presets_Title => Get("Presets_Title");

    /// <summary>Save</summary>
    public static string Presets_Save => Get("Presets_Save");

    /// <summary>New preset name</summary>
    public static string Presets_NameHint => Get("Presets_NameHint");

    /// <summary>No presets yet</summary>
    public static string Presets_None => Get("Presets_None");

    /// <summary>Delete</summary>
    public static string Presets_Delete => Get("Presets_Delete");

    /// <summary>Preset limit reached</summary>
    public static string Presets_Full => Get("Presets_Full");

    /// <summary>Settings</summary>
    public static string Settings_Title => Get("Settings_Title");

    /// <summary>Language</summary>
    public static string Settings_Language => Get("Settings_Language");

    /// <summary>System language</summary>
    public static string Settings_LanguageAuto => Get("Settings_LanguageAuto");

    /// <summary>Show the Aux channel</summary>
    public static string Settings_ShowAux => Get("Settings_ShowAux");

    /// <summary>Shortcut volume step</summary>
    public static string Settings_VolumeStep => Get("Settings_VolumeStep");

    /// <summary>Show the on-screen display</summary>
    public static string Settings_Osd => Get("Settings_Osd");

    /// <summary>Display duration</summary>
    public static string Settings_OsdDuration => Get("Settings_OsdDuration");

    /// <summary>Mouse wheel over the tray icon changes volume</summary>
    public static string Settings_TrayWheel => Get("Settings_TrayWheel");

    /// <summary>Check for updates</summary>
    public static string Settings_CheckUpdates => Get("Settings_CheckUpdates");

    /// <summary>Takes effect after a restart</summary>
    public static string Settings_RestartNeeded => Get("Settings_RestartNeeded");

    /// <summary>{0:0.0} s</summary>
    public static string Settings_Seconds => Get("Settings_Seconds");

    /// <summary>Open the log folder</summary>
    public static string Settings_OpenLog => Get("Settings_OpenLog");

    /// <summary>Keyboard shortcuts</summary>
    public static string Settings_Shortcuts => Get("Settings_Shortcuts");

    /// <summary>Version {0}</summary>
    public static string Settings_Version => Get("Settings_Version");

    /// <summary>Back</summary>
    public static string Panel_Back => Get("Panel_Back");

    /// <summary>Version {0} is available</summary>
    public static string Update_Available => Get("Update_Available");

    /// <summary>Download</summary>
    public static string Update_Download => Get("Update_Download");

    /// <summary>You are up to date</summary>
    public static string Update_UpToDate => Get("Update_UpToDate");

    /// <summary>Skip</summary>
    public static string Update_Skip => Get("Update_Skip");

}
